version: "3"
services:
  redis:
    image: redis
    networks:
      - webapp

  webapp:
    image: test1:latest
    environment:
      REDIS_HOST: redis
    networks:
      - webapp
    ports:
      - "8080:8080"

networks:
  webapp:
